### ISSUE TITLE
Figure out how to make cra compatible with React Cosmos

### ISSUE THREAD

**Issue by dankolbman** [kids-first/kf-ui-data-tracker#1021]
Currently running `yarn build` or `yarn start` will overwrite the `tsconfig.json` with `noEmit: true`. This will break React Cosmos which requires `noEmit: false`. Preferably we should see if we can prevent create-react-app from overwriting this file or how to make React Cosmos work with `noEmit: true`.

**Comment by shanewilson** [comment]
Stuff like this is why I'm starting to use Nextjs for everything - CRA can just be so hostile to devs sometimes.

It might be worth considering if now is a good time to be building out a component library though. It can be easier to have the components emerge organically from the pages of the app instead of trying to define them ahead of time. This way also helps determine which props you need to expose so you don't spend too much time worrying about what should be exposed and what should be built-in.

As a contrived example, this button component: 
https://github.com/kids-first/kf-ui-data-tracker/blob/master/src/%40next/components/atoms/Button/Button.tsx

It has a very flexible api for button colour where you can pass any of the available tailwind values, but realistically we probably don't need buttons of every colour. Limiting the choices to something like primary/secondary or cta/subtle would cover most use cases and give consistency to the overall look of the app. It is hard to tell though which values need to be exposed until we can see them used in real pages.

**Comment by dankolbman** [comment]
If we can work out a way to have both the new stuff written up in nextjs while old stuff is slowly ported over, we would be happy to go with that approach. Anything that makes the build config more tolerable works for me.

For the component library, the idea of abstracting components when needed is a good approach and I think it will be one  we follow. It's also the approach we took with the current app, but we have struggled to go back later and pull out general components and so we have multiple implementations of the same thing floating around. A lot of that is perhaps because we did not have a clear architecture for how we should create and reuse components, which is why we thought it best to lay that out now. The button component was more of an example of how a solidified component may look, although yes it was forced and did not come out of design needs.

**Comment by shanewilson** [comment]
> nextjs while old stuff is slowly ported over

It might be less hassle to make this change after the legacy app is removed. The main changes would be at the page/app level but the components should be a direct port.

> but we have struggled to go back later and pull out general components and so we have multiple implementations of the same thing floating around

this is certainly a valid concern and it probably an issue that every app will have to deal with at some point. 

>  we did not have a clear architecture for how we should create and reuse components

yea this is fair, setting up the infrastructure will make it easier to move out components when needed. As long as the workflow wasn't to build components first then try to use them in app it should be fine.

Why choose Cosmos over something like Storybook? I don't have extensive experience with either but the storybook people made https://www.chromatic.com/ which looks pretty cool and it probably has better support with CRA.

**Comment by dankolbman** [comment]
>  It might be less hassle to make this change after the legacy app is removed.

Definitely, but right now the plans seem to be to make that happen very gradually. This means we'll have to suffer through setting up CRA to handle the new stuff.

> Why choose Cosmos over something like Storybook?

From past experience, Storybook is pretty heavy and comes with a lot of dependencies. This also has required a lot of webpack tweaking to get it to build nicely and we had issues with older versions breaking quite often. Cosmos has been a lot easier to get started with, but I haven't found a way to get it to build with no additional webpack config yet.
Chromatic looks cool, but it's yet another dependency on storybook and I don't think we really have the design intensity or team in place to justify the additional process.
