### ISSUE TITLE
Data empowerment vignettes

### ISSUE THREAD

**Issue by shanewilson** [kids-first/kf-ui-data-tracker#1056]
### Creating/Inviting a User

Can a user login/signup on their own?

Can a user exist without an Organization?

What auth providers do we support?

Do we store user data in postgres?

What are we using for User IDs?

What is the process for inviting a user to an org?

Can you invite a User that already exists?

### Creating a new Organization

Can a user create organizations or does it require a Data Tracker admin?

Are organizations visible if you are not in them?

Can you request to join or do you have to be invited?

### First Steps for a new User

What are the first things a new Organization admin would do before inviting other users?

What are the first things a new User would do after joining a new Organization?

### Second Steps for a User

After setting up a new Organization and inviting Users what are the main workflows that an Admin would be concerned with?

After finishing their first steps what actions and data are Users interested in?

### Long term workflows

After running an organization for a number of months/years what are some of the main issues that require admin action/intervention?

What workflows/features would make it easier for Users to work with data that goes back months/years.

**Comment by dankolbman** [comment]
> Can a user login/signup on their own?

Yes. Anyone may use SSO via Auth0 when visiting the Data Tracker which will subsequently create an account for them. Although these users will not have access to any studies until someone logs in and adds them. The preferred method of adding users is via invite emails which will add new users using referral tokens in the emails to the studies specified by the administrator.

> Can a user exist without an Organization?

Yes, for the moment. Perhaps we shall have a splash page where the user may create their own organization or request access to some of the public organizations.

> What auth providers do we support?

Right now it's Auth0 which will sit in front of any OIDC provider and more if we choose.

> Do we store user data in postgres?

Yes. When the user logs in via Auth0, we will use whatever data we get from the OIDC claims to create a user in the database.

> What are we using for User IDs?

We currently use the `sub` claim from the JWTs we get from Auth0.

> What is the process for inviting a user to an org?

This is not implemented yet, but it will look similar to how we do invites for studies:

1) Administrator goes to team view of organization
2) Administrator uses invite button to add a new member
3) Administrator specifies an email address to send the invite to
4) Administrator specifies what role the new member will have in the organization
5) Administrator specifies studies to add the new member to as a collaborator (maybe optional since there is more configuration around their study permissions)
6) User recieves email with invitation for organization
7) User clicks referral link which will first have them log in (or create account if doesn't exist) then will add them under the desired org and studies

The referral tokens are passed with url params and contain only the id. That id in the database is associated with the desired orgs and studies and roles.

> Can you invite a User that already exists?

Yes. The referral token flow , in fact, requires an authenticated user to process correctly.

> Can a user create organizations or does it require a Data Tracker admin?

For the first iteration, we will allow anyone in our "Administrators" permission group to create orgs. In the future when we refactor our permission model, we will probably reserve this for superusers. Although there really isn't much harm in allowing anyone to create orgs.

> Are organizations visible if you are not in them?

This isn't planned at the moment except for superuser administrators.

> Can you request to join or do you have to be invited?

For now it's invite only.

> What are the first things a new Organization admin would do before inviting other users?

The creator of a new organization would, after specifying high-level details of their org, create one or more studies in their organization. This onboard funnel isn't intended to occur frequently and will most likely be handled by our internal team.

> What are the first things a new User would do after joining a new Organization?

Depends on the user persona. An Investigator would likely upload a new document or version to their study.

> After setting up a new Organization and inviting Users what are the main workflows that an Admin would be concerned with?

Organization administrators are interested in the following starting with the most common:
1) Managing the org's studies (creating, modifying, adding collaborators)
2) Creating releases of their studies
3) Managing the org's data submission templates
4) Managing the org's data (hooking up storage, high-level stats about usage)
5) Modifying the data release process (adding new release services)

> After finishing their first steps what actions and data are Users interested in?

Depends on persona. Investigators are only interested if there are requests for changes in the data they submitted. Analysts are interested in knowing when new files arrive. Coordinators are interested in when releases occur.

> Long term workflows

Not quite sure what you're getting at with these. In Kids First, we have a lot of 'status' like things where only a couple studies out of dozens will be 'active' at any given time. So things like the accumulation of studies would be a good consideration but I'm not sure if this is an example of 'long term workflows' or not.

I'm going to work on some user journey maps to help with exploring some of the things it looks like you're after.
