### ISSUE TITLE
always open Basic Info form in edit mode

### ISSUE THREAD

**Issue by bdolly** [kids-first/kf-ui-data-tracker#501]
feedback from `Admin` role users suggest to always open the Basic Info Form in edit mode as there is no use case for a read-only mode. This should alwasy show the Step progress indicators as well as form field descriptions 

🤔 maybe also add a `Save` button where the `Edit`/`Cancel` button currently is 

## Current Edit mode 
<img width="1178" alt="Screen Shot 2019-10-07 at 4 23 29 PM" src="https://user-images.githubusercontent.com/1334131/66345852-de565000-e91e-11e9-8da4-fc9f3a282efc.png">

**Comment by allisonheath** [comment]
So thinking about this more - I feel like these days instead of a whole edit view, you land on a page like this and you have a pencil icon or similar that allows you to edit each field and then save/cancel in place when done. It's either that or the saving is done in real time as you're typing so you don't have to remember to click the save button. And then lastly, if we keep the whole page editable view, then some indication that there's unsaved changes is likely needed?

**Comment by bdolly** [comment]
good point, I think something like that might have been in the original invision mockups but hasn't gotten implemented yet. 

@dankolbman maybe this is a good case to make an epic to roll this out app wide or just have components things more modularized like we've been talking about
